### ISSUE TITLE
Not working on Windows 7 x64

### ISSUE THREAD

**Issue by Pir8pete** [morrisonbrett/BlackVueDownloader#10]
I was getting this error -> https://github.com/morrisonbrett/BlackVueDownloader/issues/6
Now with .43+ I'm getting this error;

'BlackVueDownloader.exe' is not recognized as an internal or external command, operable program or batch file.

see screenshots
![untitled-1](https://cloud.githubusercontent.com/assets/25421389/23106978/9de7e38a-f6c3-11e6-99e9-e096ab090152.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/25421389/23106980/9dea4b2a-f6c3-11e6-95eb-5ee8de4d8f4b.jpg)
![untitled-3](https://cloud.githubusercontent.com/assets/25421389/23106979/9de9b8c2-f6c3-11e6-8083-617ab11de746.jpg)

https://pixhost.org/show/1438/37432019_untitled-1.jpg
https://pixhost.org/show/1438/37432020_untitled-2.jpg
https://pixhost.org/show/1438/37432021_untitled-3.jpg

**Comment by bruce-armstrong** [comment]
The command prompt window shows that the cd isn't changing the directory to the C: drive.  It's still in the D: drive   That's why it can't find the executable.

**Comment by morrisonbrett** [comment]
Command prompt doesn't work that way. You can't change directories in that way. First select the drive, then cd to the directory.  You can also add the BlackVueDownloader to your path, which will make the .exe file available to any directory on your drive(s).

**Comment by Pir8pete** [comment]
I found my mistake, I had BackVueDownloader  left out the l
