### ISSUE TITLE
Possible to sort file list by date ascending before starting download?

### ISSUE THREAD

**Issue by bruce-armstrong** [morrisonbrett/BlackVueDownloader#11]
I'm getting a lot of 404 errors in my nightly download.  I think it's because some of the older files are getting overwritten by new "parking" mode clips before the download reaches them.

Processing File: 20170226_181632_PF.mp4
Downloading video file: http://10.99.77.1/Record/20170226_181632_PF.mp4
Downloaded video file: http://10.99.77.1/Record/20170226_181632_PF.mp4
Processing File: 20170226_181632_PR.mp4
Downloading video file: http://10.99.77.1/Record/20170226_181632_PR.mp4
Downloaded video file: http://10.99.77.1/Record/20170226_181632_PR.mp4
Processing File: 20170226_154044_NF.mp4
Downloading video file: http://10.99.77.1/Record/20170226_154044_NF.mp4
Exception: One or more errors occurred. (Request to http://10.99.77.1/Record/20170226_154044_NF.mp4 failed with status code 404 (Not Found).)
Downloading gps file: http://10.99.77.1/Record/20170226_154044_N.gps
Exception: One or more errors occurred. (Request to http://10.99.77.1/Record/20170226_154044_N.gps failed with status code 404 (Not Found).)
Downloading 3gf file: http://10.99.77.1/Record/20170226_154044_N.3gf
Exception: One or more errors occurred. (Request to http://10.99.77.1/Record/20170226_154044_N.3gf failed with status code 404 (Not Found).)
Processing File: 20170226_154044_NR.mp4
Downloading video file: http://10.99.77.1/Record/20170226_154044_NR.mp4
Exception: One or more errors occurred. (Request to http://10.99.77.1/Record/20170226_154044_NR.mp4 failed with status code 404 (Not Found).)
Processing File: 20170226_154345_NF.mp4
Downloading video file: http://10.99.77.1/Record/20170226_154345_NF.mp4
Exception: One or more errors occurred. (Request to http://10.99.77.1/Record/20170226_154345_NF.mp4 failed with status code 404 (Not Found).)
Downloading gps file: http://10.99.77.1/Record/20170226_154345_N.gps
Exception: One or more errors occurred. (Request to http://10.99.77.1/Record/20170226_154345_N.gps failed with status code 404 (Not Found).)
Downloading 3gf file: http://10.99.77.1/Record/20170226_154345_N.3gf
Exception: One or more errors occurred. (Request to http://10.99.77.1/Record/20170226_154345_N.3gf failed with status code 404 (Not Found).)
Processing File: 20170226_154345_NR.mp4
Downloading video file: http://10.99.77.1/Record/20170226_154345_NR.mp4
Exception: One or more errors occurred. (Request to http://10.99.77.1/Record/20170226_154345_NR.mp4 failed with status code 404 (Not Found).)

**Comment by morrisonbrett** [comment]
That's probably the case. It can't download them fast enough. Unfortunately it's a limitation of the WiFi speed you're getting. The only way to fix this is to see if you can get an improved WiFi speed (doubtful, if it's the Dashcam that's the bottleneck) OR change your Dashcam settings to record lower-res video -> smaller file sizes -> faster downloads.
