### ISSUE TITLE
Automatic download

### ISSUE THREAD

**Issue by somejavadev** [morrisonbrett/BlackVueDownloader#15]
Hi,  
Awesome idea, exactly what I was looking for. More of a general question than an issue, I am just curious what your setup is, do you have a "Power Magic Pro" or "Power Magic Battery Pack" which leaves your cam on while parked (parking mode) and then have a computer download the files via a cron when your car is in range with its ignition off? Also would either of those "Power Magic" products work for this?

**Comment by morrisonbrett** [comment]
I have the Power Magic Pro. Yes, you can setup a scheduled task / cron to repeat, and setup the operating system to keep trying to connect to the DashCam WiFi. Once it "appears" as available, the OS will connect, and the job will start doing its work.

A future version of the software I'll have WiFi info as part of the setup, so the program does the WiFi connectivity / scheduling internally.
