### ISSUE TITLE
RaspberryPi build

### ISSUE THREAD

**Issue by somejavadev** [morrisonbrett/BlackVueDownloader#16]
Hi, is there a possibility to run/build this project on a RaspberryPi (ARM) platform?

Running the normal bash execution gives the following error:

`-bash: ./BlackVueDownloader: cannot execute binary file: Exec format error`

I tried a couple of things without success:

-Using the mono runtime.
-Ubuntu 14 runtimes.

What I do see is that I can install ubuntu server arm addition on the Pi. There seems to be a "ubuntu.16.04-arm" runtime one can use when building the project which might just do it.

I am currently starting up a Windows VM to see if I can compile the project on it. I am not too familiar with dotnet but will see if I can get the build going. Will let you know how it is going.

**Comment by morrisonbrett** [comment]
I think there's a way to add ARM as a build target.

**Comment by morrisonbrett** [comment]
Need to do this. Marking as an enhancement.

**Comment by morrisonbrett** [comment]
I'll do it. Give me a few days. :-)

**Comment by simonrb2000** [comment]
Legend! Guess I'm running cat 5 to the garage then 🤣

**Comment by morrisonbrett** [comment]
Working on this today. Will have a fix shortly.

**Comment by simonrb2000** [comment]
Really appreciate this 👍👍👍

**Comment by morrisonbrett** [comment]
v1.1.5: Updated project to support linux-arm. Download the latest [release](https://github.com/morrisonbrett/BlackVueDownloader/releases/tag/v1.1.5) and look for it in the `artifacts/` folder.
