### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by theroninhunter** [morrisonbrett/BlackVueDownloader#2]
Hi,

I'm a fairly novice Windows user but how do I run your script? 

I have a server 2012R2 box with your files bit unsure how to execute it.

**Comment by morrisonbrett** [comment]
I need to update the README.

Essentially, download the zipped release.
Unzip into a new folder
Run the .EXE file with the IP address of the camera - that should work

Once you confirm that works you can setup a Scheduled Task to have it run constantly.

**Comment by theroninhunter** [comment]
Hi,


Thanks, I released I downloaded the source code rather than a release zip.


It works perfectly with a scheduled task.


Thanks for your development of this fantastic tool.


Kind regards,


Lewis Brooks

Get Outlook for Mobile






On Mon, Aug 8, 2016 at 5:45 PM +0100, "Brett Morrison" <notifications@github.com> wrote:





I need to update the README.

Essentially, download the zipped release.
Unzip into a new folder
Run the .EXE file with the IP address of the camera - that should work

Once you confirm that works you can setup a Scheduled Task to have it run constantly.

---

**Comment by morrisonbrett** [comment]
@theroninhunter Thanks so much for your kind words.  I really just built this for myself but figured why not upload the code and setup an automated build in case others want to use it.  You're the only person that I know of that's using it - and I'm so glad someone else has found it useful.

I have it running too as a scheduled task in my garage and archiving all the footage to a large hard drive.

**Comment by morrisonbrett** [comment]
Readme updated!
