### ISSUE TITLE
Support Ubuntu 18.04

### ISSUE THREAD

**Issue by PanderMusubi** [morrisonbrett/BlackVueDownloader#21]
Please, support Ubuntu 18.04 and also document how to build from source on Ubuntu.

**Comment by morrisonbrett** [comment]
Good idea.

**Comment by durig-mdsol** [comment]
I'm currently running it without significant issue on 18.04.  The only problem I have, and I do not believe it's related to 18.04, is it doesn't seem to timeout when I drive out of range.  I have to kill the process and let the next 5-minute cronjob start it up again.

**Comment by morrisonbrett** [comment]
v1.1.5: Updated project to support Ubuntu 18.04. Download the latest [release](https://github.com/morrisonbrett/BlackVueDownloader/releases/tag/v1.1.5) and look for it in the `artifacts/` folder.

As far as how to build, you need to clone this repo, install .NET Core for Ubuntu, and run `$ dotnet restore` and `$ dotnet build`.
