### ISSUE TITLE
Timeout under Linux

### ISSUE THREAD

**Issue by durig-mdsol** [morrisonbrett/BlackVueDownloader#24]
Would it be possible to set a flag for a timeout value?  It works great, and when my car turns off the built-in wifi also does, and the camera hops over to my home wifi.  From there it will begin downloading (no need to connect to the camera's built-in wifi, any machine on the network can reach it).  My problem is that if I get in my car to leave while it's still downloading, the process will sit and wait.  And wait.  When I get home, I notice no new recordings in Plex (I download directly to a directory setup as a Library).  I have to kill the downloader process and let the cronjob that runs every 5 minutes start it again.

**Comment by morrisonbrett** [comment]
Done. Completed in v1.1.4 https://github.com/morrisonbrett/BlackVueDownloader/releases/tag/v1.1.4
