### ISSUE TITLE
Re-Downloading Files

### ISSUE THREAD

**Issue by ladyx** [morrisonbrett/BlackVueDownloader#3]
First - I love this script, thank you. You've made these cams worth owning!

While I love the idea of the temp dir for partially downloaded files, unfortunately it appears to re-download files each time I run it. 

I too have a scheduled task that runs:
netsh wlan disconnect
netsh wlan connect name="gremlin1" interface="Wi-Fi"
START /WAIT C:\dashcam\BlackVueDownloader.exe 10.99.77.1 c:\dashcam\files\front
netsh wlan disconnect
netsh wlan connect name="gremlin2" interface="Wi-Fi"
timeout /t 30
START /WAIT C:\dashcam\BlackVueDownloader.exe 10.99.77.1 c:\dashcam\files\rear\
netsh wlan disconnect
exit

Is there a way to check to see if the file exists and then if it doesn't, queue it for download? I see a bunch of commented out pieces of your script, that may do this but I'm unsure.

Also, how do you handle deleting old files, is there a way to send a delete request after the files are downloaded?

Thanks,
Annie

**Comment by morrisonbrett** [comment]
Thanks for the comment. The way the script is designed, it doesn't distinguish between copying front and rear - it copies everything from the Dashcam.  Looking at your script, you're initiating 2 launches, but with a front / rear target.  You will end up copying all files to both.

There is code to detect if the file exists, and if so, skip it.

As far as I know, the BlackVue camera protocol doesn't support a method for deleting files from the camera / card over http.
