### ISSUE TITLE
[enhancement request] check if file exists before downloading it

### ISSUE THREAD

**Issue by blysik** [morrisonbrett/BlackVueDownloader#5]
First, this project is awesome, thanks!  Next, a small request:

```
Processing File: 20170201_071020_PF.mp4
Downloading video file: http://10.99.77.1/Record/20170201_071020_PF.mp4
Exception: The file '/Volumes/Volume_1/Backups/Record/20170201_071020_PF.mp4' already exists.
```
Can you check if the file exists before downloading it?

**Comment by morrisonbrett** [comment]
Thanks @blysik. It does indeed do that. It will only copy if the file doesn't exist.  You can safely ignore that warning. That may have been because the file was partially downloaded.
