### ISSUE TITLE
Not working on Windows 7

### ISSUE THREAD

**Issue by Pir8pete** [morrisonbrett/BlackVueDownloader#6]
I can't seem to get this working on windows 7.  I have install every Visual C++ package and I still get this error.  -> https://pixhost.org/show/1405/37254937_untitled-1.jpg
My windows 10 worked right away.

Any idea's?

**Comment by morrisonbrett** [comment]
It's probably a missing Win7 specific library. I'll add it to the build artifacts and post a fix soon.  Thanks for finding.

**Comment by morrisonbrett** [comment]
OK. I published a new release with Windows 7 artifacts that should include all runtime libraries and solve this issue. https://github.com/morrisonbrett/BlackVueDownloader/releases/tag/v1.0.43

**Comment by Pir8pete** [comment]
With .43+ I'm getting this error;

'BlackVueDownloader.exe' is not recognized as an internal or external command, operable program or batch file.

see screenshots
![untitled-1](https://cloud.githubusercontent.com/assets/25421389/23106978/9de7e38a-f6c3-11e6-99e9-e096ab090152.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/25421389/23106980/9dea4b2a-f6c3-11e6-95eb-5ee8de4d8f4b.jpg)
![untitled-3](https://cloud.githubusercontent.com/assets/25421389/23106979/9de9b8c2-f6c3-11e6-8083-617ab11de746.jpg)

https://pixhost.org/show/1438/37432019_untitled-1.jpg
https://pixhost.org/show/1438/37432020_untitled-2.jpg
https://pixhost.org/show/1438/37432021_untitled-3.jpg

**Comment by Pir8pete** [comment]
thank you for getting on this so fast, I appreciate it
