### ISSUE TITLE
Downloading same files

### ISSUE THREAD

**Issue by theroninhunter** [morrisonbrett/BlackVueDownloader#7]
Hi,

I use Task Scheduler to start the process each time WiFi connects or every hour but it constantly downloads files I already have in the destination folder so it stores them in the tmp dir.

Should it always download every file and then block up the tmp directory when the file already exists  or is it meant to check if the file exists already before downloading the file from the camera?

**Comment by theroninhunter** [comment]
Downloading video file: http://10.99.77.1/Record/20170217_165759_NF.mp4
Exception: Cannot create a file when that file already exists
Downloading gps file: http://10.99.77.1/Record/20170217_165759_N.gps
Exception: Cannot create a file when that file already exists
Downloading 3gf file: http://10.99.77.1/Record/20170217_165759_N.3gf
Exception: Cannot create a file when that file already exists
Processing File: 20170217_165759_NR.mp4
Downloading video file: http://10.99.77.1/Record/20170217_165759_NR.mp4
Exception: Cannot create a file when that file already exists
Processing File: 20170217_165924_PF.mp4
Downloading video file: http://10.99.77.1/Record/20170217_165924_PF.mp4
Exception: Cannot create a file when that file already exists
Processing File: 20170217_165924_PR.mp4
Downloading video file: http://10.99.77.1/Record/20170217_165924_PR.mp4
Exception: Cannot create a file when that file already exists
Processing File: 20170217_170023_PF.mp4
Downloading video file: http://10.99.77.1/Record/20170217_170023_PF.mp4
Exception: Cannot create a file when that file already exists
Processing File: 20170217_170023_PR.mp4
Downloading video file: http://10.99.77.1/Record/20170217_170023_PR.mp4
Exception: Cannot create a file when that file already exists
Processing File: 20170217_170127_PF.mp4
Downloading video file: http://10.99.77.1/Record/20170217_170127_PF.mp4
Exception: Cannot create a file when that file already exists
Processing File: 20170217_170127_PR.mp4
Downloading video file: http://10.99.77.1/Record/20170217_170127_PR.mp4

**Comment by theroninhunter** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20906710/23097328/1be2c4b2-f629-11e6-9540-beba5b5f41fc.png)

**Comment by morrisonbrett** [comment]
Can you try this?  Delete everything in your _tmp directory, run the program, and when this happens again, attach the log output of the program to this issue.  It will really help me troubleshoot.

**Comment by morrisonbrett** [comment]
Actually, I think I see what has happened, at some point it must have failed copying from _tmp to Record. I think I can resolve this by:

Checking if the file already exists not just in the Record, but also in _tmp.  If it exists in _tmp, move it.

Thanks for finding this problem.  I can code a fix very quickly for this.

**Comment by morrisonbrett** [comment]
Thought about it more.  This won't work.  Because it could exist in the _tmp directory but be a partial.  That's the whole point of the _tmp directory, to ensure it's FULLY downloaded before it's "done".  Unfortunately, the protocol of the Dashcam does not allow me to check the file size before downloading.  If it did, it would allow me to test if it's fully downloaded.  The only way to get the file size is to fully download it.

I'm going to add a fix where it will download successfully, even if it already exists.

**Comment by morrisonbrett** [comment]
Resolved with this commit: https://github.com/morrisonbrett/BlackVueDownloader/commit/d64ed66e591d596a49979fae95a576ee9dee1d44

Please download latest release: https://github.com/morrisonbrett/BlackVueDownloader/releases

**Comment by theroninhunter** [comment]
Done but the issue persists.

Strangely it works perfectly when called upon in CMD, _TMP directory is empty etc however if I run the task in Task Scheduler the files then clog the _TMP directory

**Comment by theroninhunter** [comment]
It seems to be a Task Scheduler issue but I cannot figure out what is causing the fault
