### ISSUE TITLE
Feature Request: Logfile

### ISSUE THREAD

**Issue by theroninhunter** [morrisonbrett/BlackVueDownloader#8]
Is it possible to add a log option/tag to the .exe file?

I can obviously add >> LOGFILE.txt to my cmd in Task scheduler but my coding is poor and I am not sure how to create a txt file with todays date.

**Comment by theroninhunter** [comment]
I have created this BAT file which does the job for me

set TDay=%date:~0,2%
set TMonth=%date:~3,2%
set TYear=%date:~6,4%

G:\BlackVueDownloader\artifacts\win10-x64\BlackVueDownloader.exe 10.99.77.1 G:\BlackVueDownloader\BlackVue_Recordings >> G:\BlackVueDownloader\BlackVue_Recordings\Logs\Log_%TDay%-%TMonth%-%TYear%.txt

**Comment by morrisonbrett** [comment]
Good feature request

**Comment by tiernano** [comment]
should hopefully be fixed in #22

**Comment by morrisonbrett** [comment]
Fixed in https://github.com/morrisonbrett/BlackVueDownloader/pull/22
